### ISSUE TITLE
Stargate Tech 2 Crafting suggsestions

### ISSUE THREAD

**Issue by devensiv** [OneDayStudios/StargateMC-Public#30]
**Describe the solution you'd like**
new crafting recipe for "Transport Ring Platform" (id:1627)
N = Naquadah Alloy (6335)
S = Stone Slab (44)
C = Steel Casing (1054:8) / Machine Frame (Basic) (166ß)
[S ;S ;S]
[N;C;N]
[N;E;N]

new Recipie or removal of personal shield 5856
Z = Crude ZPM (6350)
N = Naquadah Alloy (6335)
F = Force Field Emitter (6628:11)
A = Atomic alloy (4831)
[A;Z;A]
[N;F;N]
[N;N;N]

**Describe alternatives you've considered**
The recipes are just an simple idea from how it could be if they are to cheap/to expensive fell free to contact me and i can create new ones

**Additional context**
Both items are enabled in SgTech 2 config and not craftable.

**Comment by BenFRC5147** [comment]
I've already created recipes and had them merged into the server, until a client update is issued try adding a file I will give to you on discord to your 

.technic/modpacks/StargateMC/scripts folder

**Comment by StargateMC** [comment]
Thatd only work in single player.
Closing as a duplicate.

**Comment by BenFRC5147** [comment]
It works in MP as you've merged my pull request to add it to the server, no?

**Comment by StargateMC** [comment]
When did I put it in the server, and why wouldnt I have let it on the client also lol
