### ISSUE TITLE
Stargates Do Not Dial In Orbit

### ISSUE THREAD

**Issue by Maxstripe** [OneDayStudios/StargateMC-Public#31]
**Describe the bug**
Gates dont work in orbit

**To Reproduce**
1. dial a gate in orbit
2. 
3. 
4. 

**Expected behavior**
gate should dial up as normal. gate did not dial and instead disconnected me
with a fatal error

**Screenshots**

**Versions (please complete the following information):**
 - Client Version:
 - Additional mods you have installed in your client:

**Additional context**
Add a link to a [gist](https://gist.github.com/) of any errors.

**Comment by StargateMC** [comment]
Hi Max, I believe I've fixed this one. Please jump on test when you have some time.
