### ISSUE TITLE
Earthquake Nerf / Balance

### ISSUE THREAD

**Issue by Nerion1** [OneDayStudios/StargateMC-Public#35]
**Describe the solution you'd like**
Earthquakes should have counter measures blocks or ways to prevent them happening in an area or have them be a rarer occurence.

**Describe alternatives you've considered**
"Tectonic Plate Stabilisers" which would essentially prevent earthquakes happening in a radius around that block as the block "stabilises" the earthquake.
Alternatively, make the occurrence rarer and away from player blocks (really does a LOT of damage in the area)

**Additional context**
N/A

**Comment by StargateMC** [comment]
EQ's are disabled now. Not worth the hassle yet.
