### ISSUE TITLE
Pam's Harvestcraft

### ISSUE THREAD

**Issue by Nerion1** [OneDayStudios/StargateMC-Public#38]
**Name of the mod**:
Pam's Harvestcraft
**Mod Version Recomended**:
Pam's HarvestCraft 1.7.10Lb.jar
**Link to mod page:**
https://minecraft.curseforge.com/projects/pams-harvestcraft

**Items this mod contains that allow for cross wireless communication or item/entity/fluid/block transfer:**

**Reason to add this mod:**

This will make the pack better by adding many more food types into the game and encourages creating different types of food to survive instead of the regular ways to create food.
It will also add a feeling of uniqueness to each world.

It also adds:
80 new crops (including cotton for string)
6 garden bushes to find and harvest for crops (pick up bushes or let them spread like mushrooms)
50 fruit or item bearing trees
19 new fish (catch with normal fishing rod)
Simple Beekeeping (including candle blocks, wax/honey blocks, hardened leather armor, wax as fuel)
1400+ new items and foods

**Recommended configuration:**

N/A

**Additional context**

This does changed the vanilla recipes for some food so may need to change it in the configs if its a problem (I think it only changes the way bread is made but you can make it later easier once you've collected flour etc)

**Comment by StargateMC** [comment]
This was added :)
